import Head from 'next/head';

import Footer from '../components/Footer';
import Header from '../components/Header';
import axios from 'axios';
// import MenuList from '../components/MenuList';
// import axios from 'axios';
import CategoryCard from '../components/CategoryCard';
import Featured from '../components/Featured';
import { useState } from 'react';
import { Add } from '../components/Add';
import AddButton from '../components/AddButton';

const Home = ({ ProductList, isAdmin }) => {
  const [close, setClose] = useState(true);
  return (
    <div>
      <Head>
        <title>Automated Customer Handling System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Featured ProductList={ProductList} />
      {isAdmin && <AddButton setClose={setClose} />}
      {!close && <Add setClose={setClose} />}
      <h2 className="text-4xl py-12 font-bold text-center italic">
        List of our products that are super healthy !
      </h2>
      <div className="grid md:grid-cols-3 lg:grid-cols-4 gap-14  ">
        <CategoryCard
          image="/img/MEAT.jpg"
          name="Special Food"
          des="Fresh raw Meat"
        />
        <CategoryCard
          image="/img/sandwich.jpg"
          name="Fasting Food"
          des="Cholesterol free foods"
        />
        <CategoryCard
          image="/img/Alchol.jpg"
          name="Alcohol Drinks"
          des="Enjoy your drink"
        />
        <CategoryCard
          image="/img/HD.jpg"
          name="Hot Drinks"
          des=" Special Testy Macchiato."
        />
        <CategoryCard image="/img/SD.jpg" name="Soft Drink" />
      </div>
      <Footer />
    </div>
  );
};
export default Home;
export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || '';
  let isAdmin = false;
  if (myCookie.token === process.env.TOKEN) {
    isAdmin = true;
  }
  const res = await axios.get('http://localhost:3000/api/prod');
  return {
    props: {
      ProductList: res.data,
      isAdmin,
    },
  };
};
